<a href="https://colab.research.google.com/github/pragneshrana/SignalProcessing_MachineLearning/blob/main/LSTM_Human_Activity_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Signal Processing and Machine Learning
---



### What is Signal?
- Signal is just a fucntion form to represent the information
- It combines physical simulation, mathematics and information

### What is signal processing ?
- It convert signals into another form
- Information exraction and interpretation 
    - Speech recognition
    - Computer vision

#### Examples:
 - Audio Recording : analong pressure wave is converted into one-dimentional array
 - Photos : Analog scene of light is samples using CCD array and stored as a two-dimentional array
 - Text : Collection of char which further signes with 16 bit number
 - Ratings : movies, books are stores using 0-5
 

Process: 

Model : Voices -> Feature Extrcation -> Pitch / MMCC -> Model Training 

Unknown Voice : Feature Extraction -> Pitch / MMCC -> Prediction using Model -> Speaker


#### In case of human body, 
- Activity signal -> featre extraction -> Model training -> Activity Inference

(Ref : http://web.stanford.edu/class/ee269/Lecture1.pdf)

- Generate the dataset
    - Data sourcces
    - Simulation
    - Labelling and Supervised learning 
- Preprocess and tranform data
    - Pre-Processing
    - Transformation
    - Feature extraction
    - Visulization by time, frquency, and time-frequency domain
- Develope Predictive Models
    - Refrence Models
    - Hardware-Acceleated training 
    - Analyze and tune hyper-parameter
    - Time series models : Visual Inspection of over time
    - Frequency domain analysis: Time series domain shows signal's energy distributed over time whereas, frequency domain representation includes information on the phase shift that must be applied to each frequency component in order to recover the original time signal with a combination of all the individual frequency components (FFT o DFT)
    - **LSTM for human Activity recognition (HAR)**
        - sensor based HAR
            - wearables for humanbody
        - External Device
        - Sensory output data -> input data segmentation -> LSTM based model -> combine with per time step prediction 
        - Ref : https://www.mdpi.com/1424-8220/17/11/2556/htm
             - They have used three models, 
                 - Unidirectional LSTM
                 - Bidirectional LSTM
                 - Cascade Bidorectional LSTM
- Accelerate and Deploy
    - Apps
    - Enterprise Systems
    - Embedded Devices and Hardware
    
     

For the sake of example, Human Activity dataset is used and LSTM model is applied to predict human activity.


About this Dataset

The Human Activity Recognition database was built from the recordings of 30 study participants performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors. The objective is to classify activities into one of the six activities performed.

In [3]:
import numpy as np
import pandas as pd
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
train = pd.read_csv('https://raw.githubusercontent.com/pragneshrana/SignalProcessing_MachineLearning/main/data/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/pragneshrana/SignalProcessing_MachineLearning/main/data/test.csv')

In [5]:
train.columns


Index(['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z',
       'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X',
       ...
       'fBodyBodyGyroJerkMag-kurtosis()', 'angle(tBodyAccMean,gravity)',
       'angle(tBodyAccJerkMean),gravityMean)',
       'angle(tBodyGyroMean,gravityMean)',
       'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)',
       'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'subject', 'Activity'],
      dtype='object', length=563)

In [6]:
train.shape

(7352, 563)

In [7]:
train.head()


tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject  Activity
0           0.288585          -0.020294  ...        1  STANDING
1           0.278419          -0.016411  ...        1  STANDING
2           0.279653          -0.019467  ...        1  STANDING
3           0.279174          -0.026201  ...        1  STANDING
4           0.276629          -0.016570  ...        1  STANDING

[5 rows x 563 columns]

In [8]:
test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject  Activity
0           0.257178          -0.023285  ...        2  STANDING
1           0.286027          -0.013163  ...        2  STANDING
2           0.275485          -0.026050  ...        2  STANDING
3           0.270298          -0.032614  ...        2  STANDING
4           0.274833          -0.027848  ...        2  STANDING

[5 rows x 563 columns]

In [9]:
test.shape

(2947, 563)

In [10]:
X_train = train.iloc[:,:-2]
Y_train = train.iloc[:,-1]
print(X_train.shape)
print(Y_train.shape)

(7352, 561)
(7352,)


In [11]:
X_test = test.iloc[:,:-2]
Y_test = test.iloc[:,-1]
print(X_test.shape)
print(Y_test.shape)

(2947, 561)
(2947,)


In [42]:
TRAIN_LEN = len(X_train)  
TEST_LEN = len(X_test)  
NUM_STEPS = X_train.shape[0] 
NUM_FEATURES = X_train.shape[1]
NUM_HIDDEN = 32
NUM_CLASSES = 6
LR = 0.0025
LAMBDA = 0.0020
NUM_ITERS = TRAIN_LEN * 100  
BATCH_SIZE = 1024

print(X_test.shape, Y_test.shape, X_train.shape, Y_train.shape)
print(NUM_INPUT)

(2947, 561) (2947,) (7352, 561) (7352,)
561


In [13]:
def LSTM_RNN(_X, _weights, _biases):
    _X = tf.transpose(_X, [1, 0, 2])
    _X = tf.reshape(_X, [-1, NUM_INPUT]) 
    _X = tf.nn.relu(tf.matmul(_X, _weights['hidden']) + _biases['hidden'])
    _X = tf.split(_X, NUM_STEPS, 0) 
    lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(NUM_HIDDEN, forget_bias=1.0, state_is_tuple=True)
    lstm_cell_2 = tf.contrib.rnn.BasicLSTMCell(NUM_HIDDEN, forget_bias=1.0, state_is_tuple=True)
    lstm_cells = tf.contrib.rnn.MultiRNNCell([lstm_cell_1, lstm_cell_2], state_is_tuple=True)
    outputs, states = tf.contrib.rnn.static_rnn(lstm_cells, _X, dtype=tf.float32)
    lstm_last_output = outputs[-1]
    return tf.matmul(lstm_last_output, _weights['out']) + _biases['out']


def next_batch(_train, step, batch_size):
    shape = list(_train.shape)
    shape[0] = batch_size
    batch_s = np.empty(shape)

    for i in range(batch_size):
        index = ((step-1)*batch_size + i) % len(_train)
        batch_s[i] = _train[index] 

    return batch_s


def one_hot(y_):
    y_ = y_.reshape(len(y_))
    n_values = int(np.max(y_)) + 1
    return np.eye(n_values)[np.array(y_, dtype=np.int32)]

In [43]:

regressor = keras.Sequential([layers.LSTM(units = NUM_HIDDEN, activation = 'relu', return_sequences = True, input_shape = (NUM_STEPS, NUM_FEATURES)), #input shape looks like (batch_size, time_steps, units)
                        layers.LSTM(units =NUM_HIDDEN,  return_sequences = True),
                        layers.Dropout(0.2),
                        layers.LSTM(units=NUM_HIDDEN,unit_forget_bias=1.0),
                        layers.Dense(15),
                        layers.Dense(6)])
print(regressor.summary())



Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_55 (LSTM)               (None, 7352, 32)          76032     
_________________________________________________________________
lstm_56 (LSTM)               (None, 7352, 32)          8320      
_________________________________________________________________
dropout_21 (Dropout)         (None, 7352, 32)          0         
_________________________________________________________________
lstm_57 (LSTM)               (None, 32)                8320      
_________________________________________________________________
dense_36 (Dense)             (None, 15)                495       
_________________________________________________________________
dense_37 (Dense)             (None, 6)                 96        
Total params: 93,263
Trainable params: 93,263
Non-trainable params: 0
_________________________________________________

In [21]:
regressor.compile(optimizer='adam', loss = 'mean_squared_error')
regressor.fit(X_train, Y_train, epochs=DISP_ITER, batch_size=BATCH_SIZE)

correct_pred = tf.equal(tf.argmax(pred,1), tf.argmax(y,1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

y_pred = regressor.predict(x)

Epoch 1/20000


ValueError: ignored

In [28]:
test_losses = []
test_accuracies = []
train_losses = []
train_accuracies = []


sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))
init = tf.global_variables_initializer()
sess.run(init)
saver = tf.train.Saver()

step = 1
while step * BATCH_SIZE <= NUM_ITERS:
    batch_xs = next_batch(X_Train, step, BATCH_SIZE)
    batch_ys = one_hot(next_batch(y_Train, step, BATCH_SIZE))

    
    _, loss, acc = sess.run([optimizer, cost, accuracy],feed_dict={x: batch_xs, y: batch_ys})
    train_losses.append(loss)
    train_accuracies.append(acc)
    
    
    if (step*BATCH_SIZE % DISP_ITER == 0) or (step == 1) or (step * BATCH_SIZE > NUM_ITERS):
        print("Iteration " + str(step*BATCH_SIZE) +  ":Batch Loss = " + "{:.3f}".format(loss) + ", Accuracy = {}".format(acc))
        loss, acc = sess.run([cost, accuracy], feed_dict={x: X_Test,y: one_hot(y_Test)})
        test_losses.append(loss)
        test_accuracies.append(acc)
        print("Test: " + "Batch Loss = {}".format(loss) + ", Accuracy = {}".format(acc))
    step += 1



one_hot_predictions, accuracy, final_loss = sess.run([pred, accuracy, cost],feed_dict={x: X_Test,y: one_hot(y_Test)})

test_losses.append(final_loss)
test_accuracies.append(accuracy)

print("RESULT: " + "Batch Loss = {}".format(final_loss) + ", Accuracy = {}".format(accuracy))



AttributeError: ignored

In [43]:
model = keras.Sequential([layers.Embedding(input_dim=1000, output_dim=64),
                          layers.LSTM(128),
                          layers.Dense(10)])
# Add an Embedding layer expecting input vocab of size 1000, and
# output embedding dimension of size 64.
# Add a LSTM layer with 128 internal units.
# Add a Dense layer with 10 units.
model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 64)          64000     
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               98816     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 164,106
Trainable params: 164,106
Non-trainable params: 0
_________________________________________________________________


In [7]:
c = tf.constant([[1.0, 2.0,4.0,5.2], [3.0, 4.0,6,6.3],[3.0, 8.0,9.0,4.3],[8.0, 12.0,6.0,7.3]])
# d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
# e = tf.matmul(c, d)
print(c)

tf.Tensor(
[[ 1.   2.   4.   5.2]
 [ 3.   4.   6.   6.3]
 [ 3.   8.   9.   4.3]
 [ 8.  12.   6.   7.3]], shape=(4, 4), dtype=float32)


In [9]:
tf.transpose(c,[1, 0, 2])

InvalidArgumentError: ignored